name: pymarad
dependencies:
  - python>=3.6
  - numpy>=1.20.1
  - matplotlib>=3.3.4
  - scipy>=1.6.1
  - pandas>=1.2.3
  - wbgapi>=1.0.5
  - matplotlib-venn>=0.11.6
  - datapackage>=1.15.2
  - scipy>=1.6.2
  - netCDF4>=1.5.7
  - plotly>=5.6.0